# Trino Hive Catalog - Worker
connector.name=hive

# Hive Metastore
hive.metastore.uri=thrift://<ip-node-1>:9083

# SeaweedFS S3 como storage
hive.s3.endpoint=http://<ip-node-1>:8333
hive.s3.path-style-access=true
hive.s3.aws-access-key=
hive.s3.aws-secret-key=
hive.s3.ssl.enabled=false
hive.s3select-pushdown.enabled=true

# Permissoes
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.allow-add-column=true
hive.allow-drop-column=true
hive.allow-rename-column=true

# Performance
hive.max-partitions-per-scan=1000000
hive.max-outstanding-splits-size=256MB
hive.domain-compaction-threshold=512
