# Trino Worker Configuration
coordinator=false
http-server.http.port=8080
discovery.uri=http://trino-coordinator:8080

# Memory
query.max-memory=50GB
query.max-memory-per-node=8GB

# Node
log.path=/data/trino/var/log

# Spill
spill-enabled=true
spiller-spill-path=/data/trino/spill
